---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "1433"
    port: {{ .Values.service.port }}
    targetPort: 1433
  selector:
    app: mssql
