# Default values for mssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/kontinu/plusti-bootcamp/master/mssql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2017-latest"

service:
  type: ClusterIP
  port: 1433

config:
  saPassword: "th3Passw0rd"
